name: Selenium e2e test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Jest
        run: npm install --save-dev jest

      - name: Install Selenium WebDriver
        run: npm install --save-dev selenium-webdriver

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          export PATH=$PATH:/usr/lib/chromium-browser/

      - name: Run end-to-end tests
        run: npm run test:e2e
